# Generated by Django 4.2.2 on 2023-07-27 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Shop', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='product_status',
            field=models.CharField(choices=[('published', 'Published'), ('disabled', 'Disabled'), ('rejected', 'Rejected'), ('in_review', 'In Review'), ('draft', 'Drafts')], max_length=10),
        ),
        migrations.AlterField(
            model_name='productreview',
            name='rating',
            field=models.IntegerField(choices=[(1, '★✰✰✰✰'), (5, '★★★★★'), (3, '★★★☆☆'), (4, '★★★★☆'), (2, '★★☆☆☆')], default=None),
        ),
    ]
