# Generated by Django 4.2.2 on 2023-07-27 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Shop', '0004_customer_image_customer_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='vendor',
            name='Vendor_status',
            field=models.CharField(choices=[('rejected', 'Rejected'), ('review', 'In Review'), ('approved', 'Approved')], default=1, max_length=20),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='cartorder',
            name='product_status',
            field=models.CharField(choices=[('process', 'Processing'), ('delivered', 'Delivered'), ('shipped', 'Shipped')], default='processing', max_length=10),
        ),
        migrations.AlterField(
            model_name='product',
            name='product_status',
            field=models.CharField(choices=[('draft', 'Drafts'), ('disabled', 'Disabled'), ('rejected', 'Rejected'), ('published', 'Published'), ('in_review', 'In Review')], max_length=10),
        ),
        migrations.AlterField(
            model_name='productreview',
            name='rating',
            field=models.IntegerField(choices=[(5, '★★★★★'), (1, '★✰✰✰✰'), (4, '★★★★☆'), (2, '★★☆☆☆'), (3, '★★★☆☆')], default=None),
        ),
    ]
