# Generated by Django 4.2.2 on 2023-07-28 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Shop', '0005_vendor_vendor_status_alter_cartorder_product_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cartorder',
            name='product_status',
            field=models.CharField(choices=[('delivered', 'Delivered'), ('process', 'Processing'), ('shipped', 'Shipped')], default='processing', max_length=10),
        ),
        migrations.AlterField(
            model_name='product',
            name='product_status',
            field=models.CharField(choices=[('published', 'Published'), ('disabled', 'Disabled'), ('draft', 'Drafts'), ('in_review', 'In Review'), ('rejected', 'Rejected')], max_length=10),
        ),
        migrations.AlterField(
            model_name='productreview',
            name='rating',
            field=models.IntegerField(choices=[(4, '★★★★☆'), (1, '★✰✰✰✰'), (2, '★★☆☆☆'), (5, '★★★★★'), (3, '★★★☆☆')], default=None),
        ),
        migrations.AlterField(
            model_name='vendor',
            name='Vendor_status',
            field=models.CharField(choices=[('In Review', 'In Review'), ('Rejected', 'Rejected'), ('Approved', 'Approved')], default='In Review', max_length=20),
        ),
        migrations.AlterField(
            model_name='vendor',
            name='image',
            field=models.ImageField(upload_to='user_img'),
        ),
    ]
