# Generated by Django 4.2.2 on 2023-08-16 05:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Shop', '0006_alter_cartorder_product_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cartorder',
            name='product_status',
            field=models.CharField(choices=[('shipped', 'Shipped'), ('delivered', 'Delivered'), ('process', 'Processing')], default='processing', max_length=10),
        ),
        migrations.AlterField(
            model_name='product',
            name='product_status',
            field=models.CharField(choices=[('published', 'Published'), ('draft', 'Drafts'), ('rejected', 'Rejected'), ('disabled', 'Disabled'), ('in_review', 'In Review')], max_length=10),
        ),
        migrations.AlterField(
            model_name='product',
            name='tags',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Shop.tags'),
        ),
        migrations.AlterField(
            model_name='productreview',
            name='rating',
            field=models.IntegerField(choices=[(1, '★✰✰✰✰'), (3, '★★★☆☆'), (2, '★★☆☆☆'), (4, '★★★★☆'), (5, '★★★★★')], default=None),
        ),
        migrations.AlterField(
            model_name='vendor',
            name='Vendor_status',
            field=models.CharField(choices=[('Rejected', 'Rejected'), ('In Review', 'In Review'), ('Approved', 'Approved')], default='In Review', max_length=20),
        ),
    ]
