# Generated by Django 4.2.2 on 2023-08-16 05:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Shop', '0007_alter_cartorder_product_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cartorder',
            name='product_status',
            field=models.CharField(choices=[('shipped', 'Shipped'), ('process', 'Processing'), ('delivered', 'Delivered')], default='processing', max_length=10),
        ),
        migrations.AlterField(
            model_name='product',
            name='product_status',
            field=models.CharField(choices=[('published', 'Published'), ('disabled', 'Disabled'), ('in_review', 'In Review'), ('rejected', 'Rejected'), ('draft', 'Drafts')], max_length=10),
        ),
        migrations.AlterField(
            model_name='productreview',
            name='rating',
            field=models.IntegerField(choices=[(3, '★★★☆☆'), (5, '★★★★★'), (1, '★✰✰✰✰'), (4, '★★★★☆'), (2, '★★☆☆☆')], default=None),
        ),
        migrations.AlterField(
            model_name='vendor',
            name='Vendor_status',
            field=models.CharField(choices=[('In Review', 'In Review'), ('Approved', 'Approved'), ('Rejected', 'Rejected')], default='In Review', max_length=20),
        ),
    ]
